import BachiMadurez from "../assets/bachi-madurez.jpg";
import TercerCiclo from "../assets/tercer-ciclo.jpg";
import Primaria from "../assets/primaria.jpg";
import CursosTecnicos from "../assets/cursos-tecnicos.jpg";
import CursosLibres from "../assets/cursos-libres.jpg";
import Talleres from "../assets/talleres.jpg";
import CursosPortugues from "../assets/cursos-portugues.jpg";
import CursosIngles from "../assets/cursos-ingles.jpg";

export const coursesInfo = [
  {
    paramName: "bachillerato-madurez",
    thumbnails: BachiMadurez,
    category: "Bachillerato",
    paragraph: "Diseñado para personas adultas que quieren terminar el colegio sin estrés, con acompañamiento real y resultados comprobados.",
    title: "Bachillerato por Madurez",
    description: "Obtén la preparación necesaria para superar tus exámenes con éxito.",
    note: "Este programa está pensado para personas que retoman sus estudios después de años. No importa tu nivel actual: reforzamos desde la base y avanzamos paso a paso hasta que domines los contenidos evaluados en Bachillerato por Madurez.",
    quote: "Ofrecemos una preparación efectiva para aprobar los exámenes de Bachillerato por Madurez, dirigida a personas mayores de 18 años con noveno año aprobado, que desean finalizar esta etapa con seguridad, acompañamiento real y un programa enfocado en resultados, optimizando el tiempo y aumentando las probabilidades de éxito.",
    fullDescription: "Aprende a tu propio ritmo con el curso de Bachillerato por Madurez de Top Academy, diseñado específicamente para prepararte de forma clara, práctica y enfocada en aprobar las pruebas oficiales. Contarás con materiales actualizados, clases guiadas por docentes con experiencia y un acompañamiento constante que te permitirá avanzar con seguridad hasta el día del examen.",
    benefits: ["Comprender los temas evaluados en el Bachillerato por Madurez de forma clara y sin enredos.", "Estudiar con guías, ejercicios y materiales alineados a las pruebas oficiales.", "Recibir apoyo y acompañamiento de docentes especializados durante todo tu proceso de aprendizaje.", "Prepararte para las evaluaciones con simulacros y retroalimentación personalizada.", "Recibir acompañamiento académico constante durante todo el proceso.", "Llegar al examen con seguridad, preparación y confianza real."],
    badge: "30%",
    stars: "5.0",
  },
  {
    paramName: "tercer-ciclo-madurez",
    thumbnails: TercerCiclo,
    category: "Tercer Ciclo",
    paragraph: "Refuerza tus conocimientos y prepárate para el bachillerato con confianza.",
    title: "Tercer Ciclo (séptimo, octavo y noveno) por Madurez",
    note: "Este programa está diseñado para personas que retoman o continúan sus estudios después de una pausa. No importa si necesitas reforzar contenidos anteriores: comenzamos desde la base y avanzamos paso a paso, respetando tu ritmo de aprendizaje.",
    description: "Refuerza tus conocimientos y prepárate para el bachillerato con confianza.",
    quote: "Diseñado para personas a partir de los 14 años que cuentan con el título de sexto grado y desean completar Séptimo, Octavo o Noveno año de forma ordenada, acompañada y efectiva.",
    fullDescription: "Aprende a tu propio ritmo con el programa de Tercer Ciclo por Madurez de Top Academy, diseñado para acompañarte en el proceso de Séptimo, Octavo y Noveno año, reforzando las bases académicas y preparándote correctamente para avanzar al Bachillerato. Contarás con materiales estructurados, clases guiadas por docentes con experiencia y un acompañamiento constante que te permitirá comprender las materias, avanzar con seguridad y cumplir tu objetivo académico.",
    benefits: ["Comprender de forma clara los contenidos de Séptimo, Octavo y Noveno año.", "Estudiar con materiales claros, actualizados y alineados a los programas oficiales.", "Recibir acompañamiento académico constante durante todo el proceso.", "Avanzar con confianza hacia la obtención del título de Tercer Ciclo."],
    badge: "20%",
    stars: "4.9",
  },
  {
    paramName: "primaria-madurez",
    thumbnails: Primaria,
    category: "Primaria",
    paragraph: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    title: "Primaria por Madurez",
    note: "Este programa está dirigido a personas que retoman sus estudios después de una pausa. No se requieren conocimientos avanzados: comenzamos desde lo básico y avanzamos paso a paso, respetando el ritmo de aprendizaje de cada estudiante.",
    description: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    quote: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestro curso de Primaria por Madurez está diseñado para brindarte una educación sólida y motivadora que te prepare para los siguientes niveles académicos.",
    fullDescription: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestro curso de Primaria por Madurez está diseñado para brindarte una educación sólida y motivadora que te prepare para los siguientes niveles académicos.",
    benefits: ["Comprender los contenidos fundamentales del sexto grado de primaria.", "Fortalecer las bases académicas necesarias para continuar con Tercer Ciclo.", "Estudiar con materiales claros, actualizados y alineados a los programas oficiales.", "Prepararte para las evaluaciones con simulacros y retroalimentación personalizada.", "Recibir acompañamiento académico durante todo el proceso."],
    badge: "20%",
    stars: "4.8",
  },
  {
    paramName: "curso-ingles",
    thumbnails: CursosIngles,
    category: "Curso Inglés",
    paragraph: "Obtén la preparación necesaria para superar tus exámenes con éxito.",
    title: "Curso de Inglés",
    description: "Obtén la preparación necesaria para superar tus exámenes con éxito.",
    note: "Este programa está pensado para personas que retoman sus estudios después de años. No importa tu nivel actual: reforzamos desde la base y avanzamos paso a paso hasta que domines los contenidos evaluados en el curso de Inglés.",
    quote: "Obtén la preparación necesaria para superar tus exámenes con éxito. Nuestro curso de Inglés está diseñado para brindarte los conocimientos y habilidades que necesitas para triunfar en tus estudios y alcanzar tus metas académicas.",
    fullDescription: "Obtén la preparación necesaria para superar tus exámenes con éxito. Nuestro curso de Inglés está diseñado para brindarte los conocimientos y habilidades que necesitas para triunfar en tus estudios y alcanzar tus metas académicas.",
    benefits: ["Comprender los temas evaluados en el curso de Inglés de forma clara y sin enredos.", "Estudiar con guías, ejercicios y materiales alineados a las pruebas oficiales.", "Recibir apoyo y acompañamiento de docentes especializados durante todo tu proceso de aprendizaje.", "Prepararte para las evaluaciones con simulacros y retroalimentación personalizada.", "Recibir acompañamiento académico constante durante todo el proceso.", "Llegar al examen con seguridad, preparación y confianza real."],
    badge: "30%",
    stars: "5.0",
  },
  {
    paramName: "curso-portugues",
    thumbnails: CursosPortugues,
    category: "Curso Portugués",
    paragraph: "Refuerza tus conocimientos y prepárate para el bachillerato con confianza.",
    title: "Curso de Portugués",
    description: "Refuerza tus conocimientos y prepárate para el bachillerato con confianza.",
    note: "Este programa está pensado para personas que retoman sus estudios después de años. No importa tu nivel actual: reforzamos desde la base y avanzamos paso a paso hasta que domines los contenidos evaluados en el curso de Portugués.",
    quote: "Refuerza tus conocimientos y prepárate para el bachillerato con confianza. Nuestro curso de Portugués está diseñado para ayudarte a consolidar tus habilidades académicas y prepararte para los desafíos del bachillerato, asegurando una transición exitosa hacia la educación superior.",
    fullDescription: "Refuerza tus conocimientos y prepárate para el bachillerato con confianza. Nuestro curso de Portugués está diseñado para ayudarte a consolidar tus habilidades académicas y prepararte para los desafíos del bachillerato, asegurando una transición exitosa hacia la educación superior.",
    benefits: ["Comprender los temas evaluados en el curso de Portugués de forma clara y sin enredos.", "Estudiar con guías, ejercicios y materiales alineados a las pruebas oficiales.", "Recibir apoyo y acompañamiento de docentes especializados durante todo tu proceso de aprendizaje.", "Prepararte para las evaluaciones con simulacros y retroalimentación personalizada.", "Recibir acompañamiento académico constante durante todo el proceso.", "Llegar al examen con seguridad, preparación y confianza real."],
    badge: "20%",
    stars: "4.9",
  },
  {
    paramName: "cursos-tecnicos",
    thumbnails: CursosTecnicos,
    category: "Cursos Técnicos",
    paragraph: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    title: "Cursos Técnicos",
    description: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    note: "Este programa está pensado para personas que retoman sus estudios después de años. No importa tu nivel actual: reforzamos desde la base y avanzamos paso a paso hasta que domines los contenidos evaluados en los cursos técnicos.",
    quote: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestros cursos técnicos están diseñados para brindarte habilidades prácticas y conocimientos especializados que te preparen para el mundo laboral y el desarrollo profesional.",
    fullDescription: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestros cursos técnicos están diseñados para brindarte habilidades prácticas y conocimientos especializados que te preparen para el mundo laboral y el desarrollo profesional.",
    benefits: ["Adquirir habilidades técnicas específicas que te preparen para el mercado laboral.", "Participar en actividades prácticas que refuercen el aprendizaje y la aplicación de conocimientos.", "Recibir apoyo constante de docentes especializados que te guiarán en tu proceso educativo.", "Fomentar el desarrollo profesional a través de métodos interactivos y dinámicos.", "Prepararte para avanzar con éxito en tu carrera profesional con una base sólida."],
    badge: "20%",
    stars: "4.8",
  },
  {
    paramName: "cursos-libres",
    thumbnails: CursosLibres,
    category: "Cursos Libres",
    paragraph: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    title: "Cursos Libres",
    description: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    note: "Este programa está pensado para personas que retoman sus estudios después de años. No importa tu nivel actual: reforzamos desde la base y avanzamos paso a paso hasta que domines los contenidos evaluados en los cursos libres.",
    quote: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestros cursos libres están diseñados para ofrecerte una variedad de temas y habilidades que te permitan explorar tus intereses y expandir tus conocimientos de manera flexible y accesible.",
    fullDescription: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestros cursos libres están diseñados para ofrecerte una variedad de temas y habilidades que te permitan explorar tus intereses y expandir tus conocimientos de manera flexible y accesible.",
    benefits: ["Explorar una amplia gama de temas y habilidades que te interesen.", "Estudiar a tu propio ritmo y según tu disponibilidad.", "Acceder a materiales y recursos variados para enriquecer tu aprendizaje.", "Recibir apoyo y orientación de docentes especializados cuando lo necesites.", "Ampliar tus conocimientos y habilidades de manera flexible y accesible."], 
    badge: "20%",
    stars: "4.8",
  },
  {
    paramName: "talleres",
    thumbnails: Talleres,
    category: "Talleres",
    paragraph: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    title: "Talleres",
    description: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante.",
    note: "Este programa está pensado para personas que retoman sus estudios después de años. No importa tu nivel actual: reforzamos desde la base y avanzamos paso a paso hasta que domines los contenidos evaluados en los talleres.",
    quote: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestros talleres están diseñados para brindarte experiencias prácticas y colaborativas que fomenten el aprendizaje activo y el desarrollo de habilidades en diversas áreas de interés.",
    fullDescription: "Desarrolla las bases del aprendizaje en un entorno divertido y estimulante. Nuestros talleres están diseñados para brindarte experiencias prácticas y colaborativas que fomenten el aprendizaje activo y el desarrollo de habilidades en diversas áreas de interés.",
    benefits: ["Desarrollar habilidades fundamentales para el aprendizaje en un ambiente positivo y motivador.", "Participar en actividades y ejercicios diseñados para fortalecer la comprensión y el pensamiento crítico.", "Recibir apoyo constante de docentes especializados que te guiarán en tu proceso educativo.", "Fomentar la curiosidad y el amor por el aprendizaje a través de métodos interactivos y dinámicos.", "Prepararte para avanzar con éxito a niveles educativos superiores con una base sólida."],
    badge: "20%",
    stars: "4.8",
  },
];
